name: Cypress
on: [push, pull_request, workflow_call, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Dependencies
        run: npm i
      - name: Test
        run: npm run cypress:run
